### ISSUE TITLE
Interactive display of Segmentations

### ISSUE THREAD

**Issue by bbarad** [baradlab/surface-morphometrics-gui#3]
Display segmentations (and potentially tomograms) from a given data folder to assist users in configuration.

**Comment by hemanthkapa** [comment]
# Issue: Implement Directory based Segmentation Preview 

## Context
Users need to be able to preview segmentation files when selecting a data directory in the configuration editor. This helps verify correct file selection and configure necessary parameters appropriately. 

## Current Behavior
Currently, when users select a data directory, there is no immediate preview functionality of the segmentation files contained within. 

## Desired Behavior
When a user selects a data directory in the configuration editor:
1. System should scan the directory for supported files (.mrc)
2. First valid MRC file should be automatically loaded and displayed in the napari viewer
3. Users should be able to verify their selection through the preview before proceeding

## Tasks
- [ ] feat: Directory scanning functionality
       - Directory path change detection
       - filter files for .mrc extension and load
       - handle empty directory case
- [ ] feat: Simple napari viewer integration
- [ ] feat: Layer management (removing old layer before loading new one)

## Resources
https://github.com/alisterburt/napari-tomoslice

**Comment by hemanthkapa** [comment]
Tagging @bbarad @braughtg for review 😄
